import 'package:get/get.dart';

class Mylocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "english",
          "2": "عربي",
          "more_of_aplocation":"مزيد من التطبيقات",
          "Share":"المشاركه",
          "supor_center":"مركز الدعم",
          "login_out":"تسجيل الخروج",
          "archaeological":"أثري ",
          "tourist":" سياحي",
          "rock":"الرئج",
          "nominations":"ألترشيحات",
          "recommendation": "توصيات",
          "welcome": "مرحبا",
          "homepage": "الصفحة الرئيسية",
          "title": "إحجز",
          "fuvorite": "ألمفضله",
          "home": "الرئيسية",
          "hotels": "الفنادق",
          "spaces": "الإستراحات",
          "tours": "جولات سياحية",
          "cars": "السيارات",
          "hotel": "فندق",
          "space": "إستراحة",
          "tour": "جولة سياحية",
          "car": "سيارة",
          "adults": "البالغين",
          "children": "الأطفال",
          "people": "الأشخاص",
          "best_tours": "أفضل الجولات السياحية",
          "apply": "تطبيق",
          "filtering": "فلترة",
          "price": "السعر",
          "lowest_price": "أدنى سعر",
          "highest_price": "أعلى سعر",
          "stars_rating": "عدد النجمات",
          "what_is_your_destination_?": "ماهي وجهتك ؟",
          "hotel_name": "إسم الفندق",
          "date": "التاريخ",
          "from": "من",
          "to": "إلى",
          "search": " بحث عن فنادق",
          "best_hotels": "أفضل الفنادق",
          "best_spaces": "أفضل الإستراحات",
          "best_cars": "أفضل السيارات",
          "sign_out": "تسجيل خروج",
          "my_account": "حسابي",
          "re_search": "إعادة البحث",
          "featured": "مميز",
          "night": "ليلة",
          "nights": "ليالي",
          "details": "تفاصيل",
          "rooms": "الغرف",
          "you_are_not_signed_in": "انت غير مسجل",
          "login": "تسجيل دخول",
          "Click_Here": " أضغط هنا",
          "sign_up": "انشاء حساب",
          "email": "الإيميل",
          "phone": "رقم الهاتف",
          "name": "الاسم",
          "please_enter_email": "من فضلك أدخل الإيميل",
          "password": "كلمة المرور",
          "this_cant_be_empty": "لا يمكن تركه فارغاً",
          "create_new_account": "إنشاء حساب جديد",
          "first_name": "الاسم الاول",
          "last_name": "اللقب",
          "please_enter_your_first_name": "من فضلك أدخل اسمك الأول",
          "please_enter_your_name": "من فضلك أدخل اسمك",
          "please_enter_your_last_name": "من فضلك أدخل اللقب",
          "please_enter_your_phone_number": "من فضلك أدخل رقم الهاتف",
          "please_enter_your_password": "من فضلك أدخل كلمة المرور",
          "already_have_an_account?": "هل تملك حساباً ؟",
          "verify_your_phone": "التحقق من الرقم",
          "a_verification_code_has_been_sent_to_your_phone":
              "تم إرسال كود تحقق إلى رقمك",
          "enter_the_phone_verification_code_here": "أدخل كود التحقق هنا",
          "enter_code": "أدخل الكود",
          "size": "المساحة",
          "m2": "m2",
          "extra_prices": "أسعار إضافية",
          "total": "الإجمالي",
          "reserve_now": "إحجز الآن",
          "done": "  تم  ",
          "rial": "ريال",
          "hours": "ساعات",
          "Completed": "مكتمل",
          "completed": "مكتمل",
          "Processing": "قيد المعالجة",
          "processing": "قيد المعالجة",
          "Confirmed": "تم التأكيد",
          "confirmed": "تم التأكيد",
          "Cancelled": "ملغي",
          "cancelled": "ملغي",
          "Paid": "مدفوع",
          "paid": "مدفوع",
          "Unpaid": "غير مدفوع",
          "unpaid": "غير مدفوع",
          "Partial_payment": "مدفوع جزئي",
          "partial_payment": "مدفوع جزئي",
          "booking_id": "رقم الحجز",
          "my_booking": "حجوزاتي",
          "booking_history": "سجل الحجوزات",
          "booking_total": "إجمالي قيمة الحجز",
          "booking_type": "نوع الحجز",
          "booking_confirmation": "تأكيد الحجز",
          "search_results": "نتائج البحث",
          "signing_went_wrong": "خطأ تسجيل",
          "an_error_occurred_while_logging_in_Please_log_in_again":
              "حصل خطأ أثناء تسجيل الدخول , يرجى إعادة تسجيل الدخول مرة أخرى",
          "attributes": "الخصائص",
          "description": "الوصف",
          "car_features": "مواصفات السيارة",
          "door_no": "عدد الأبواب",
          "passengers_no": "عدد الركاب",
          "gear": "ناقل الحركة",
          "baggage": "الأمتعة",
          "room_details": "تفاصيل الغرفة",
          "room_features": "مواصفات الغرفة",
          "beds_no": "عدد الأسرة",
          "adults_no": "عدد البالغين",
          "children_no": "عدد الأطفال",
          "time": "الوقت",
          "ok": "حسناً",
          "tourism plece": "اماكن سيحايه",
          "cancel": "إلغاء",
          "write_notes_and_press_ok": "أكتب ملاحظاتك ثم انقر على موافق",
          "booking_details": "تفاصيل الحجز",
          "days_no": "عدد الأيام",
          "daily_price": "سعر اليوم",
          "total_price": "إجمالي السعر",
          "extra_services_total_price": "إجمالي أسعار الخدمات الإضافية",
          "notes": "ملاحظات",
          "confirm": "تأكيد",
          "rooms_details": "تفاصيل الغرف",
          "room_name": "اسم الغرفة",
          "no.": "العدد",
          "rating_the": "تقييم ال",
          "favorite": "المفضلة",
          "pay_on_arrival": "الدفع عند الوصول",
          "pay_with_bank": "الدفع إلى الحساب البنكي",
          "got_to_home": "العودة للرئيسية",
          "got_to_booking_history": "الذهاب لسجل الحجوزات",
          "not_complete": "غير مكتمل",
          "you_can_review_after_making_completed_booking":
              "تستطيع التقييم عندما إكتمال حجز واحد على الأقل",
          "successfully_reviewed": "تم التقييم بنجاح",
          "your_rating_has_been_successfully_added": "تم إضافة تقييمك بنجاح",
          "sponsored": "ممول",
          "tour_is_not_available": "الجولة السياحية غير متاحة",
          "you_have_been_signed_out": "تم تسجيل خروجك",
          "booking_successful": "تم إرسال طلبك , سيتم الرد عليك قريباً",
          "rooms_are_not_available": "الغرف المحجوزة غير متاحة",
          "car_is_not_available": "السيارة غير متاحة",
          "space_is_not_available": "الإستراحة غير متاحة",
          "data_error": "خطأ في البيانات",
          "make_sure_you_are_connected_to_the_internet_and_try_again":
              "تأكد من إتصالك بالإنترنت وحاول مرة أخرى",
          "contact_with_social_media": "تواصل عبر منصات التواصل الإجتماعي",
          "contact": "تواصل معنا",
          "or_with_these_numbers": "أو عبر الأرقام التالية",
          "share_the_app": "شارك التطبيق",
          "about": "حول",
          "developed_by": "برمجة وتطوير",
          "settings": "الإعدادات",
          "info_edit": "تعديل البيانات",
          "password_edit": "تعديل كلمة المرور",
          "Update successfully": "تم التعديل بنجاح",
          "old_password": "كلمة المرور القديمة",
          "new_password": "كلمة المرور الجديدة",
          "confirm_new_password": "تأكيد كلمة المرور الجديدة",
          "update": "تحديث",
          "it_should_match_the_password":
              "يجب أن تكون مطابقة لكلمة المرور الجديدة",
          "city": "المدينة",
          "rest": "إستراحة",
          "forgot_password?": "نسيت كلمة المرور ؟",
          "Password changed successfully !": "تم تغيير كلمة المرور بنجاح",
          "Your current password does not matches with the password you provided. Please try again.":
              "كلمة المرور الحالية لا تتطابق مع كلمة المرور المرسلة , يرجى إعادة المحاولة",
          "must_be_more_than_6_characters": "يجب أن تكون أكثر من 6 حروف",
          "to_city": "مدينة الوصول",
          "from_city": "مدينة الإنطلاق",
          "starts_from": "تبدأ من",
          "cities": "المدن",
          "discount": "خصم",
          "mostvisite": "ألاكثر زياره",
          "optional": "إختياري",
          "tourismplece": " اماكن سياحيه ",
          "restrunt": "مطاعم"
        },
        "en": {
          "1": "english",
          "2": "arabic",
          "welcome": "welcome",
          "homepage": "homepage",
          "title": "Ehjjiz",
          "home": "Home",
          "mostvisite": "most visites ",
          "recommendation": "recommendation",
          "hotels": "Hotels",
          "spaces": "Space",
          "tours": "Tours",
          "cars": "Cars",
          "hotel": "Hotel",
          "space": "Space",
          "tour": "Tour",
          "tourismplece": "tourism plece ",
          "car": "Car",
          "adults": "Adults",
          "children": "Children",
          "people": "People",
          "best_tours": "Best Tours",
          "apply": "Apply",
          "filtering": "Filtering",
          "price": "Price",
          "lowest_price": "Lowest Price",
          "highest_price": "Highest Price",
          "stars_rating": "Stars Rating",
          "what_is_your_destination_?": "what is your destination ?",
          "hotel_name": "Hotel Name",
          "date": "Date",
          "from": "from",
          "to": "to",
          "Click_Here": "Click Here",
          "search": "Search",
          "best_hotels": "Best Hotels",
          "best_spaces": "Best Spaces",
          "best_cars": "Best Cars",
          "sign_out": "Sign Out",
          "my_account": "My Account",
          "re_search": "Re-Search",
          "featured": "Featured",
          "night": "night",
          "nights": "nights",
          "details": "Details",
          "rooms": "Rooms",
          "you_are_not_signed_in": "You're' not signed in",
          "login": "Login",
          "sign_up": "Sign up",
          "email": "Email",
          "phone": "Phone",
          "name": "Name",
          "please_enter_email": "Please enter email",
          "password": "Password",
          "this_cant_be_empty": "This can't be empty",
          "create_new_account": "Create new account",
          "first_name": "First Name",
          "last_name": "Last Name",
          "please_enter_your_first_name": "Please enter your first name",
          "please_enter_your_last_name": "Please enter your last name",
          "please_enter_your_name": "Please enter your name",
          "please_enter_your_phone_number": "Please enter your phone number",
          "please_enter_your_password": "Please enter your password",
          "already_have_an_account?": "Already Have an Account ?",
          "verify_your_phone": "Verify Your Phone",
          "a_verification_code_has_been_sent_to_your_phone":
              "A verification code has been sent to your phone",
          "enter_the_phone_verification_code_here":
              "Enter the phone verification code here",
          "enter_code": "Enter Code",
          "size": "size",
          "m2": "م2",
          "extra_prices": "Extra Prices",
          "total": "Total",
          "reserve_now": "Reserve Now",
          "done": "done",
          "rial": "Rial",
          "restrunt": "restrunt",
          "hours": "Hours",
          "Completed": "Completed",
          "completed": "Completed",
          "Processing": "Processing",
          "processing": "Processing",
          "Confirmed": "Confirmed",
          "confirmed": "Confirmed",
          "Cancelled": "Cancelled",
          "cancelled": "Cancelled",
          "Paid": "Paid",
          "paid": "Paid",
          "Unpaid": "Unpaid",
          "unpaid": "Unpaid",
          "Partial_payment": "Partial Payment",
          "partial_payment": "Partial Payment",
          "booking_id": "Booking No.",
          "my_booking": "My Booking",
          "booking_history": "Booking History",
          "booking_total": "Booking Total",
          "booking_type": "Booking Type",
          "booking_confirmation": "Booking Confirmation",
          "search_results": "Search Results",
          "signing_went_wrong": "Signing went wrong",
          "an_error_occurred_while_logging_in_Please_log_in_again":
              "An error occurred while logging in. Please log in again",
          "attributes": "Attributes",
          "description": "Description",
          "car_features": "Car Features",
          "door_no": "Doors number",
          "passengers_no": "Passengers Number",
          "gear": "Gear",
          "baggage": "Baggage",
          "room_details": "Room Details",
          "room_features": "Room Features",
          "beds_no": "Beds No",
          "adults_no": "Adults No",
          "children_no": "Children No",
          "time": "Time",
          "ok": "Ok",
          "cancel": "Cancel",
          "write_notes_and_press_ok": "Write Notes And Press Ok",
          "booking_details": "Booking Details",
          "days_no": "Days No.",
          "daily_price": "Daily Price",
          "total_price": "Total Price",
          "extra_services_total_price": "Extra Services Total Price",
          "notes": "Notes",
          "confirm": "Confirm",
          "rooms_details": "Rooms Details",
          "room_name": "Room Name",
          "no.": "No.",
          "rating_the": "Rating the ",
          "favorite": "Favorite",
          "pay_on_arrival": "Pay on arrival",
          "pay_with_bank": "Pay With Bank",
          "got_to_home": "Home",
          "got_to_booking_history": "Booking History",
          "not_complete": "Not Complete",
          "you_can_review_after_making_completed_booking":
              "You can review after making completed booking",
          "successfully_reviewed": "Successfully Reviewed",
          "your_rating_has_been_successfully_added":
              "Your rating has been successfully added",
          "sponsored": "Sponsored",
          "tour_is_not_available": "Tour is not available",
          "you_have_been_signed_out": "You have been signed out",
          "booking_successful":
              "Your request has been sent, we will reply to you shortly",
          "rooms_are_not_available": "Rooms are not available",
          "car_is_not_available": "car_is_not_available",
          "space_is_not_available": "Space is not available",
          "data_error": "Data Error",
          "make_sure_you_are_connected_to_the_internet_and_try_again":
              "Make sure you are connected to the internet and try again",
          "contact_with_social_media": "Contact in social media",
          "contact": "Contact",
          "or_with_these_numbers": "Or with these numbers",
          "share_the_app": "Share the app",
          "about": "About",
          "developed_by": "Developed By",
          "settings": "Settings",
          "info_edit": "Info Edit",
          "password_edit": "Password Edit",
          "Update successfully": "Update Successfully",
          "old_password": "Old Password",
          "new_password": "New Password",
          "confirm_new_password": "Confirm New Password",
          "update": "Update",
          "it_should_match_the_password": "It should match the new password",
          "city": "City",
          "rest": "Rest",
          "forgot_password?": "Forgot password ?",
          "Password changed successfully !": "Password changed successfully !",
          "Your current password does not matches with the password you provided. Please try again.":
              "Your current password does not matches with the password you provided. Please try again.",
          "must_be_more_than_6_characters": "Must be more than 6 characters",
          "to_city": "Destination",
          "from_city": "From",
          "starts_from": "Starts from",
          "cities": "Cities",
          "discount": "Discount",
          "optional": "Optional",
          "fuvorite": "fuvorite",
          "more_of_aplocation":"More Of Aplocations",
          "Share":"Share",
          "supor_center":"Supor Center",
          "login_out":"Login Out",
          "archaeological":"archaeological",
          "tourist":"Tourist",
          "rock":"Rock",
          "nominations":"Nominations"
        },
      };
}
